import datetime as dt
import random
import smtplib

my_email = "Myemail@gmail.com"
password = "xhavgcokaxiikfko"
now = dt.datetime.now()
weekday = now.weekday()
if weekday == 6:
    with open("quotes.txt") as quote_file:
        all_quotes = quote_file.readlines()
        quote = random.choice(all_quotes)

    with smtplib.SMTP("smtp.gmail.com", port=587) as connection:
        connection.starttls()
        connection.login(user=my_email, password=password)
        connection.sendmail(
            from_addr=my_email,
            to_addrs="senderMail@gmail.com",
            msg=f"Subject:Sunday Motivation\n\n{quote}\n\nThis mail is generated by python code."
        )
